[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"

[functions]
directory = "functions"

[build]
publish = "public"

[dev]
port = 3300
publish = "public" 
autoLaunch = true

[[redirects]]
from = "/post-message/*"
to = "/.netlify/functions/post-message"
status = 200
force = true

[context.production]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
